export const hotelOptions = {
  "hotel-rak-inn": {
    name: "RAK Inn 3★",
    stars: 3,
    price: 250,
    features: ["Clean rooms", "Basic amenities", "Good location", "Free WiFi"],
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    location: "Ras Al Khaimah",
  },
  "hotel-marina-4": {
    name: "Marina View 4★",
    stars: 4,
    price: 450,
    features: ["Sea view", "Restaurant", "Pool", "Gym", "Room service"],
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    location: "Dubai Marina",
  },
  "atlantis-5": {
    name: "Atlantis The Palm 5★",
    stars: 5,
    price: 1200,
    features: ["Luxury suites", "Private beach", "Aquaventure", "Multiple restaurants", "Spa"],
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    location: "Palm Jumeirah",
  },
  "marriot-abu-dhabi": {
    name: "Marriott Abu Dhabi 5★",
    stars: 5,
    price: 2200,
    features: ["Presidential suite", "Butler service", "Private pool", "Michelin dining", "Helicopter pad"],
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    location: "Abu Dhabi",
  },
}

export const mealOptions = {
  veg: {
    name: "Vegetarian",
    price: 180,
    description: "Pure vegetarian meals with local and international cuisine",
    icon: "🥗",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
  },
  "non-veg": {
    name: "Non-Vegetarian",
    price: 250,
    description: "Mixed cuisine with meat, seafood, and vegetarian options",
    icon: "🍖",
    image: "https://images.unsplash.com/photo-1558030006-450675393462?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
  },
  local: {
    name: "Local Food Experience",
    price: 350,
    description: "Authentic Emirati and Middle Eastern dining experiences",
    icon: "🥘",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
  },
  none: {
    name: "None",
    price: 0,
    description: "No meals included - explore dining independently",
    icon: "🍽️",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
  },
}

export const transportOptions = {
  economy: {
    name: "Economy",
    price: 200,
    features: ["Basic sedan", "Professional driver", "Fuel included"],
    icon: "🚗",
    image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
  },
  premium: {
    name: "Premium",
    price: 450,
    features: ["Luxury sedan", "English speaking driver", "Bottled water", "WiFi"],
    icon: "🚙",
    image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
  },
  private: {
    name: "Private",
    price: 800,
    features: ["Private chauffeur", "Premium SUV", "Flexible timing", "VIP service"],
    icon: "🚐",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
  },
  shared: {
    name: "Shared",
    price: 120,
    features: ["Shared transport", "Fixed schedule", "Budget friendly", "Group travel"],
    icon: "🚌",
    image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
  },
}

export const attractionOptions = {
  "burj-khalifa": {
    name: "Burj Khalifa – Top Deck",
    price: 179,
    duration: "2 hours",
    location: "Dubai",
    features: ["World's tallest building", "Panoramic views", "Sunset experience", "VIP access"],
    icon: "🏙️",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    url: "https://www.burjkhalifa.ae",
  },
  "dubai-fountain": {
    name: "Dubai Fountain Show",
    price: 0,
    duration: "1 hour",
    location: "Dubai",
    features: ["Free attraction", "Musical fountains", "Evening shows", "Burj Khalifa views"],
    icon: "⛲",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    url: "https://www.burjkhalifa.ae",
  },
  "dubai-aqua": {
    name: "Dubai Aquarium",
    price: 0,
    duration: "1 hour",
    location: "Dubai",
    features: ["Underwater tunnel", "Marine life", "Interactive exhibits", "Family friendly"],
    icon: "🐠",
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    url: "https://www.burjkhalifa.ae",
  },
  "grand-mosque": {
    name: "Sheikh Zayed Grand Mosque",
    price: 0,
    duration: "2 hours",
    location: "Abu Dhabi",
    features: ["Free entry", "Architectural marvel", "Cultural experience", "Photography allowed"],
    icon: "🕌",
    image: "https://images.unsplash.com/photo-1464983953574-0892a716854b?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    url: "https://www.szgmc.gov.ae",
  },
  "louvre-abu-dhabi": {
    name: "Louvre Abu Dhabi",
    price: 63,
    duration: "3 hours",
    location: "Abu Dhabi",
    features: ["Art museum", "Cultural exhibits", "Architecture", "Waterfront location"],
    icon: "🏛️",
    image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    url: "https://www.louvreabudhabi.ae",
  },
  "ferrari-world": {
    name: "Ferrari World",
    price: 295,
    duration: "4 hours",
    location: "Abu Dhabi",
    features: ["Theme park", "Ferrari rides", "Indoor attractions", "Family entertainment"],
    icon: "🏎️",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    url: "https://www.ferrariworldabudhabi.com",
  },
  "desert-safari": {
    name: "Dubai Desert Safari",
    price: 250,
    duration: "6 hours",
    location: "Dubai",
    features: ["Dune bashing", "Camel ride", "BBQ dinner", "Cultural show"],
    icon: "🏜️",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    url: "https://www.desertsafari.com",
  },
  "global-village": {
    name: "Global Village",
    price: 22,
    duration: "4 hours",
    location: "Dubai",
    features: ["Cultural pavilions", "Shopping", "Entertainment", "Food stalls"],
    icon: "🌍",
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    url: "https://www.globalvillage.ae",
  },
  "ain-dubai": {
    name: "Ain Dubai",
    price: 130,
    duration: "1 hour",
    location: "Dubai",
    features: ["Observation wheel", "City views", "Sunset experience", "Photography"],
    icon: "🎡",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    url: "https://www.aindubai.com",
  },
  "miracle-garden": {
    name: "Dubai Miracle Garden",
    price: 55,
    duration: "3 hours",
    location: "Dubai",
    features: ["Flower displays", "Seasonal attraction", "Photography", "Family outing"],
    icon: "🌸",
    image: "https://images.unsplash.com/photo-1490750967868-88aa4486c946?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    url: "https://www.dubaimiraclegarden.com",
  },
  "yas-waterworld": {
    name: "Yas Waterworld",
    price: 270,
    duration: "4 hours",
    location: "Abu Dhabi",
    features: ["Water park", "Thrill rides", "Family slides", "Wave pool"],
    icon: "🌊",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    url: "https://www.yaswaterworld.com",
  },
  "jebel-jais": {
    name: "Jebel Jais Zipline",
    price: 341,
    duration: "5 hours",
    location: "Ras Al Khaimah",
    features: ["World's longest zipline", "Mountain views", "Adventure sport", "Professional guides"],
    icon: "🪂",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    url: "https://visitjebeljais.com",
  },
  "ski-dubai": {
    name: "Ski Dubai",
    price: 220,
    duration: "3 hours",
    location: "Dubai",
    features: ["Indoor skiing", "Snow park", "Penguin encounter", "Year-round snow"],
    icon: "⛷️",
    image: "https://images.unsplash.com/photo-1551524164-4876eb6e4a89?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    url: "https://www.skidxb.com",
  },
  "dubai-frame": {
    name: "Dubai Frame",
    price: 50,
    duration: "2 hours",
    location: "Dubai",
    features: ["Architectural landmark", "City views", "Historical exhibits", "Photo opportunities"],
    icon: "🖼️",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    url: "https://www.dubaiframe.ae",
  },
  "motiongate": {
    name: "Motiongate Dubai",
    price: 275,
    duration: "5 hours",
    location: "Dubai",
    features: ["Hollywood theme park", "Movie rides", "Family entertainment", "Indoor attractions"],
    icon: "🎬",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    url: "https://www.motiongatedubai.com",
  },
  "warner-bros-world": {
    name: "Warner Bros World",
    price: 295,
    duration: "5 hours",
    location: "Abu Dhabi",
    features: ["Indoor theme park", "Cartoon characters", "Family rides", "Entertainment"],
    icon: "🎭",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    url: "https://www.wbworldabudhabi.com",
  },
} 